name: 'github.daveshuckerow.chat.service'
dependencies:
  angular2: ^2.2.0
  fixnum: any
  http: ^0.11.3
  meta: any
  quiver: any
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
